Fix AttributeError: module 'unittest' has no attribute 'mock' (#302)
We only had module-level unittest import before now, but code accessing
mock through unittest.mock was working because we have a test-level
import from unittest.mock which causes unittest to gain the mock
attribute and if the test was run before other tests (those using
unittest.mock.patch) all was good. If the test was not run before them,
though, they'd fail.

Closes GH-295.