Revert "Switch from netifaces to psutil"
psutil doesn't seem to work on pypy3:

    Traceback (most recent call last):
      File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/nose/failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/nose/loader.py", line 414, in loadTestsFromName
        addr.filename, addr.module)
      File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/nose/importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/nose/importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/home/travis/build/jstasiak/python-zeroconf/test_zeroconf.py", line 17, in <module>
        import zeroconf as r
      File "/home/travis/build/jstasiak/python-zeroconf/zeroconf.py", line 35, in <module>
        import psutil
      File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/psutil/__init__.py", line 62, in <module>
        from . import _pslinux as _psplatform
      File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/psutil/_pslinux.py", line 23, in <module>
        from . import _psutil_linux as cext
    ImportError: unable to load extension module
        '/home/travis/virtualenv/pypy3-2.4.0/site-packages/psutil/_psutil_linux.pypy3-24.so':
        /home/travis/virtualenv/pypy3-2.4.0/site-packages/psutil/_psutil_linux.pypy3-24.so: undefined symbol: PyModule_GetState

Additionally netifaces turns out to be possible to install on Python 3,
therefore making it necessary to investigate the original issue.

This reverts commit dd907f2eed3768a3c1e3889af84b5dbeb700a1e7.